name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  $CHANGES
  
  ## Docker Images
  [![docker](https://github.com/cased/ssh-oauth-handlers/workflows/docker/badge.svg?branch=v$RESOLVED_VERSION)](https://github.com/cased/ssh-oauth-handlers/actions?query=workflow%3Adocker+branch%3Av$RESOLVED_VERSION)
  ```
  ghcr.io/cased/ssh-oauth-handlers:v$RESOLVED_VERSION
  ```
